In [1]:
import pandas as pd
import numpy as np
import math

In [4]:
train = pd.read_csv("../data/processed/train.csv")
test = pd.read_csv("../data/processed/test.csv")
print("Train:", train.shape)
display(train.head())
print("Test:", test.shape)
display(test.head())

Train: (88799, 6)

,reviewers,course_id,rating,date_reviews,user_id,course_idx
0,By George W,philosophy,5,2015-08-07,2736,384
1,By Konstantinos K,learning-how-to-learn,5,2015-08-07,4049,314
2,By Mohammed R,machine-learning,5,2015-08-07,5116,318
3,By Michelle F,learning-how-to-learn,5,2015-08-07,4948,314
4,By Tushar T,machine-learning,5,2015-08-07,7579,318

Test: (16342, 6)

,reviewers,course_id,rating,date_reviews,user_id,course_idx
0,By Manojkumar P,wharton-customer-analytics,4,2015-12-29,4472,542
1,By Julien H J,wharton-customer-analytics,5,2016-01-13,3783,542
2,By Jingxia P,wharton-operations-analytics,3,2016-01-14,3486,551
3,By Roussel K,python,5,2016-01-14,6470,420
4,By Manojkumar P,terrorism,4,2016-01-16,4472,501

In [6]:
print("Các cột train:", train.columns.tolist())
print("Các cột test:", test.columns.tolist())

print("\nThông tin tập train:")
train.info()

Các cột train: ['reviewers', 'course_id', 'rating', 'date_reviews', 'user_id', 'course_idx']
Các cột test: ['reviewers', 'course_id', 'rating', 'date_reviews', 'user_id', 'course_idx']

Thông tin tập train:
<class 'pandas.DataFrame'>
RangeIndex: 88799 entries, 0 to 88798
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   reviewers     88799 non-null  str
 1   course_id     88799 non-null  str
 2   rating        88799 non-null  int64
 3   date_reviews  88799 non-null  str
 4   user_id       88799 non-null  int64
 5   course_idx    88799 non-null  int64
dtypes: int64(3), str(3)
memory usage: 7.6 MB

### Baseline 1 — Popularity-Based Recommendation
Đề xuất các khoá học phổ biến nhất dựa trên số lượt đánh giá tích cực trong train

In [7]:
nguong_tich_cuc = 4
positive_train = train[
    train["rating"] >= nguong_tich_cuc
].copy()
mon_pho_bien = (
    positive_train.groupby("course_idx")["course_idx"]
    .count()
    .reset_index(name= "positive_count")
    .sort_values("positive_count", ascending= False)
)
print("Số lượt đánh giá tích cực:", len(positive_train))
print("Số khoá học có ít nhất 1 đánh giá tích cực:", len(mon_pho_bien))
display(mon_pho_bien.head(10))

Số lượt đánh giá tích cực: 81969
Số khoá học có ít nhất 1 đánh giá tích cực: 564

     course_idx  positive_count
362         362            2086
318         318            2073
420         420            1995
314         314            1893
423         423            1820
498         498            1398
121         121            1354
431         431            1297
557         557            1268
321         321            1075